language: node_js
node_js:
- 6
- 7
cache: yarn
deploy:
  provider: npm
  email: joe.grund@intel.com
  api_key:
    secure: OZCuf8xQQ+Z9K+mZAUS2/TRZxGDIk6yHHCn2CNq9spA5tUmI9J00xksKqDA0zEQQLWKjLY238dd7D/4dcbKhdHCBceUPZ5kwpWb7WQ1+9ePUEllCQ0bfFCOwb5uhE2IhBeq1CP/AhSYZ5uIG5+ktDnEil3H7hDRYsuojRjmglIdtY1OCKXrC1CTh0hmWmwTm5Gx21VGcBdwghKyLlU2mfevt9q9Lp20JPfsdAZ0OgJ4+LCHO3DzLE3UVVaLRgN+lvGQK51E065unLZ8oD8OKw0qn3i0lHS8gyobKa5FP40O+FHHoyGePbis+s12TajEUL0iSMBkkR2bKRSJLpbAaGkbFgJiTyYlJ2sVHkC50fY0GPhMDOirdyA8ZbBEjcLjBM8QnUBL6ULDwSovPkCp389s33QR3J+oILlkDx6QVcv1T5jPGuo+p2Oi0gEzaDzi8S76aPOSTmLsr2+Zw3cJRzdP03CwEV88dkOO9Cl2rB8DAMYq3Ual6wQTdXPTwyAEaC6iOEC+8JYfnWlKaydTcQPiCDJF6Lb2GbZp+QgHgXTLSf7Da2bgcLAzCsFYTMImktqY9qePtpUofESI40R1vvFRDQudOSh21S06JnrP/vwBmxHShcpO4mNs6FkYFcNPjM8SyOqnI2/zTGplIzzVHwciMBbWUtbvB4p1qOivncWk=
  on:
    tags: true
    repo: intel-hpdd/dirp
